# Generated by Django 5.2.15 on 2026-07-07 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_move_vending_models_state'),
        ('vending', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispenselog',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispense_logs', to='subscriptions.subscription'),
        ),
        migrations.AlterField(
            model_name='dispenseorder',
            name='qr_session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order', to='vending.qrsession'),
        ),
        migrations.AlterField(
            model_name='dispenseorder',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispense_orders', to='subscriptions.subscription'),
        ),
        migrations.AlterField(
            model_name='dispenseorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispense_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
